public enum TokenType {
	TK_INT,TK_FLOAT,TK_STR,TK_VOID,TK_BOOL,TK_TRUE,
	TK_FALSE,TK_FUNC,TK_FOR,TK_WHILE,TK_IF,
	TK_ELSE,TK_CONT,TK_BREAK,TK_CONST,TK_DEF,TK_DIV,
	TK_QUOT,TK_LPARENT,TK_RPARENT,TK_WS,TK_CARRET,
	TK_LBRACE,TK_RBRACE,TK_FASTAND,TK_FASTOR,TK_NOT,
	TK_MULTI,TK_DIVIDE,TK_ADD,TK_SUBTRACT;
}
