public enum TokenType {
	TK_ID,
	TK_K_INT,TK_K_FLOAT,TK_K_STR,TK_K_VOID,TK_K_BOOL,TK_K_TRUE,
	TK_K_FALSE,TK_K_FUNC,TK_K_FOR,TK_K_WHILE,TK_K_IF,
	TK_K_ELSE,TK_K_CONT,TK_K_BREAK,TK_K_CONST,TK_K_DEF,TK_K_DIV,
	TK_S_QUOT,TK_S_LEFT_PARENT,TK_S_RIGHT_PARENT,TK_S_WS,TK_S_CARRET,
	TK_S_LEFT_BRACE,TK_S_RIGHT_BRACE,TK_S_FASTAND,TK_S_FASTOR,TK_S_NOT,
	TK_S_MULTI,TK_S_DIVIDE,TK_S_ADD,TK_S_SUBTRACT;
}
